### ISSUE TITLE
Anime are only external links

### ISSUE THREAD

**Issue by bratboo101** [TheBeastLT/stremio-cdn-videos#5]
For some reason, all the streams for anime are external links now.

Did WonderfulSubs change something? Are there no longer playable streams?

**Comment by TheBeastLT** [comment]
Yeah, WS now uses replay.watch for some of they stream, which is not resolved to an actual url. So only Auto HLS streams are left.

You can try using this addon in [PMS](https://github.com/sungshon/PimpMyStremio) there it will resolve more of the urls, because some of them are IP restricted once resolved.

**Comment by bratboo101** [comment]
It works fine with PMS, thx.
